export const surpriseMePrompts = [
  "A Majestic Mountain Range at Sunrise",
  "A City of Glass and Steel at Night",
  "A Haunted Cemetery in the Fog",
  "A Robot Army on a Dystopian Battlefield",
  "A Majestic Waterfall in a Tropical Forest",
  "An Alien Planet with Multiple Moons",
  "A Futuristic Skyscraper in the Clouds",
  "A Desert Landscape with a Sandstorm Approaching",
  "A Fairy Tale Castle in a Rainbow Sky",
  "A Wild Jungle with Exotic Animals",
  "A Post-Apocalyptic City Ruin",
  "A Mythical Dragon Breathing Fire",
  "A Dreamy Beach Sunset with Palm Trees",
  "A Steampunk Train in a Desert Canyon",
  "A Haunted Ghost Ship on a Stormy Sea",
  "A Robot Uprising in a Cybernetic City",
  "A Magical Forest with Glowing Mushrooms",
  "A Gothic Cathedral on a Moonlit Night",
  "A Futuristic Hovercraft over a City River",
  "An Underwater City with Neon Lights",
  "A Mythical Phoenix Rising from the Ashes",
  "A Retro Space Station in Orbit",
  "A Snowy Mountain Peak at Dusk",
  "A Futuristic Battle in a Dark Alleyway",
  "A Haunted Mansion on a Hilltop",
  "A Tropical Island with a Volcano in the Distance",
  "A Cybernetic Being in a Virtual World",
  "A Dreamy Pastel Sky with Clouds",
  "A Magical Kingdom with a Rainbow Bridge",
  "A City of the Future with Flying Cars",
];
